server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
#    hikari:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/stevedb
    username: steve
    password: changeme
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 451262533301-lq7dovoch6acqg7radrccbk43jgmcrb4.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 639585500673293
            client-secret: d4dddcb137e4b20667dc25d2bd2fb6db
            scope:
            - email
            - public_profile

          naver:
            client-id: fgFGoXzO5Eb09oYM5Wlo
            client-secret: 9lx1yIYOAf
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/naver
            
          kakao:
            client-id: 1248fb4f90bab3a006520f8ffaf43f1b
            client-secret: 17o0Y0EeucNfY4tnImEVBpRFCoSbmBoj
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
            client-authentication-method: POST
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json 으로 받는데 response라는 키값으로 네이버가 리턴해줌
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          
